spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

logging.level.root=WARN
logging.level.tasks.manager=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

